### ISSUE TITLE
Add file assert support

### ISSUE THREAD

**Issue by Caveat4U** [ActivisionGameScience/assertpy#12]
I've started writing the file assert support in my forked branch:
https://github.com/Caveat4U/assertpy/commit/1a8642b2f8c56ca0959c6f3aafd2fb70ddeb74bf

All I've done so far is just a basic equals comparison, but before I continue, I wanted to make sure that my coding style aligns with what you have in mind. I thought about creating a subclass since I'm going to have a lot of divergent code, but I'm not sure how well that would work with the current framework.
Also, should file size be a consideration to take into account? I could read 10 characters at a time in a while loop to solve any memory concerns behind comparing 2 massive files, but wasn't sure how much effort to focus on there.
I still need to write my tests to make sure this code is solid - not ready for the pull request yet. :-)

**Comment by saturnboy** [comment]
you beat me by 5 minutes - see issue #13 for my file assertion API ideas

As a general design goal, `assertpy` is simple if nothing else. A good fluent API, plus straightforward internals.  Basically, 5-10 line assertion methods, and try to avoid anything fancy.
