### ISSUE TITLE
add file assertions

### ISSUE THREAD

**Issue by saturnboy** [ActivisionGameScience/assertpy#13]
Some API ideas:

```py
assert_that(myfile).exists()
assert_that(myfile).is_file()
assert_that(mydir).is_directory()
assert_that(myfile).is_named('foo.txt')
assert_that(myfile).is_child_of(parent_dir)
assert_that(contents_of(myfile)).starts_with('foo').contains('bar').ends_with('baz')
```

**Comment by Caveat4U** [comment]
I like the methods.
You think leaving out the equals for now though?

**Comment by Caveat4U** [comment]
Oh! I see. Using your contents_of and chaining and returning the return AssertionBuilder() object, you only have to pop open the file in one place, which is brilliant, but should there be a limitation on file size passed in?

**Comment by saturnboy** [comment]
As designed (and this could change), the `contents_of()` method is just a little helper to read the contents of a file into a string, no unicode support, no file size limitations, and no hidden magic.

The goal of `assertpy` is to help you test, not to protect our users from abusing the library.  If a tester wants to try and open a 100gb file, good for them.
