### ISSUE TITLE
update numeric assertions to work with dates

### ISSUE THREAD

**Issue by saturnboy** [ActivisionGameScience/assertpy#17]
Update these four assertions so they work correctly with dates:

```py
assert_that(123).is_greater_than(100)
assert_that(123).is_less_than(200)
assert_that(123).is_between(100, 200)
assert_that(123).is_close_to(100, 25)
```

**Comment by frodopwns** [comment]
Should these only work with datetime objects like the date-specific functions?

**Comment by saturnboy** [comment]
Let's start with `datetime`, more support could be added in the future...

**Comment by frodopwns** [comment]
Ok, have you started work on this already? If not, do you mind if I take it?
