### ISSUE TITLE
update readme with date assertions

### ISSUE THREAD

**Issue by saturnboy** [ActivisionGameScience/assertpy#18]
update the readme with section on date assertions:

* `is_before()`
* `is_after()`
* `is_equal_to_ignoring_milliseconds()`
* `is_equal_to_ignoring_seconds()`
* `is_equal_to_ignoring_time()`

and soon (see #17):

* `is_less_than()`
* `is_greater_than()`
* `is_between()`
* `is_close_to()`

**Comment by frodopwns** [comment]
@saturnboy  Mind if I take a crack at this?
