### ISSUE TITLE
correct implementation of soft assertions

### ISSUE THREAD

**Issue by argos83** [ActivisionGameScience/assertpy#53]
Hi!
   This is not a bug report, but more like a discussion kick-starter regarding soft assertions. And if we happen to agree on a different implementation, I'll be more than happy to create a PR.

What I suggest is soft assertions to be implemented as in other languages libraries. E.g [soft assertions in AssertJ](http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#soft-assertions).

Soft assertions usually have a special value in higher levels of testing than unit, e.g. integration or system tests, when the result feedback is not as fast as with unit test. 
So basically a test is more "expensive" to run in terms of resources like CPU, memory, and specially time. And we want to take the most value out of each execution.

Let's assume that I have a test that:
 - Logs in
 - Creates a new user in the system with default settings
 - And verifies that the user has a
   * default locale = X
   * default timezone = Y
   * default privileges = Z
   * etc, etc

If any of these are missing or wrong, I want the test to fail. However, with regular assertions if the locale is missing the test will fail as expected but I won't have any information whether the system meets the other requirements.

As you know, that's when soft assertions come handy. The problem I see though, is that in your implementation, you silently pass, I mean.. you print a warning in stdout, but the test will pass.  And that's a wrong approach IMO, as it requires human intervention (someone reading the screen), so those assertions won't have any effect if tests are run, for instance, in jenkins as part of CI/CD pipeline.

What I suggest is what AssertJ does. You run assertions in a group, so even if the "locale" assertion fails, you still run the "timezone" and the "privileges" assertions. After all the assertions have been executed an AssertionError is raised if at least one assertion in the group failed. The error will contain the details of all those assertions in the group that failed.

Does all this make sense to you? WDYT?

Regards!

**Comment by saturnboy** [comment]
@argos83 i'm super familiar with soft assertions in AssertJ.  The existing *soft* assertion impl is really just a warning as you pointed out, so not really an assertion at all.  Probably should rename `assert_soft()` to `assert_warn()` (or maybe `warn_that()` or `warn_if_not()` or `warn_unless()`) to avoid the confusion.  I punted on the full impl...seemed hard at the time.  Happy to see a PR!

**Comment by saturnboy** [comment]
@argos83 I think this is what you want...happy for any feedback.

Just use the `soft_assertions` context with any block of `assertpy` assertions, like this:

```py
from assertpy import assert_that, soft_assertions

with soft_assertions():
    assert_that('foo').is_length(4)
    assert_that('foo').is_equal_to('bar')
    assert_that(123).is_between(100, 200)
```

And it raises any assertion errors all at once at the end, like this:

```
AssertionError: soft assertion failures:
1. Expected <foo> to be of length <4>, but was <3>.
2. Expected <foo> to be equal to <bar>, but was not.
```

Using a context manager makes it super easy to turn a block of regular assertions into soft, and vice versa.

I also renamed the old `assert_soft` to `assert_warn`.

**Comment by argos83** [comment]
Thanks @saturnboy! That's exactly what I was looking for.
