### ISSUE TITLE
Question :: assertpy extending

### ISSUE THREAD

**Issue by rmerkushin** [ActivisionGameScience/assertpy#61]
How can i extend your library without monkey patching? I want to add some custom matchers to assert_that. How best to do this?

**Comment by saturnboy** [comment]
@rmerkushin Could you share some of your extension ideas?  Maybe they should be in the base lib.

Didn't design `assertpy` with extension in mind, that's my fault.  Monkey patching might be your best bet for now.  Alternately, I might suggest you extend the class itself:

```py
class MyAssertionBuilder(AssertionBuilder):
    pass 
    # override/add asserts here..
```

Of course a lot of the sauce is in the various helper functions, like `assert_that()`, so you'd have to copy-and-paste those.

Happy to merge PR to make extensions easier.  Any suggestions?

**Comment by rmerkushin** [comment]
Thanks for your answer! I wrote function which compare two tables (list of lists).  Example: SQL query result with CSV file with soft assertion as root idea. I think this is a bad idea to add my function in your library because it's have many dependencies. Sorry for my bad english :)

Link to my function:
https://gist.github.com/rmerkushin/d416da3d2e032ca0d949d4cf8266b50c

**Comment by saturnboy** [comment]
@rmerkushin Wow! That's awesome, and behave definitely looks like a cool BDD framework. For now, monkey patching is *definitely* the right thing to do.  I'll need to figure out a better extension mechanism for `assertpy`.

Of course, you can easily test a [list of lists](https://github.com/ActivisionGameScience/assertpy/blob/master/tests/test_list.py#L341) or a [list of dicts](https://github.com/ActivisionGameScience/assertpy/blob/master/tests/test_list.py#L359).

**Comment by alex-bes** [comment]
Hi @saturnboy! thank you for your great job on this library! I wonder if there any progress has been made on the subject since?

**Comment by saturnboy** [comment]
@alex-bes i have made some progress on a big refactor to use mixin classes (see #95) which should help. still not exactly sure what extension would look like. do you have any examples or usage patterns you could share?

**Comment by saturnboy** [comment]
@alex-bes the new `assertpy` extension system (see [docs](https://github.com/ActivisionGameScience/assertpy#extension-system---adding-custom-assertions)) is in.  it allows you to write your own assertions to do whatever you want.

**Comment by legshort** [comment]
I was looking for something like this feature and `Extension System - adding custom assertions` is just great!!

**Comment by legshort** [comment]
@saturnboy can you plz release?

**Comment by saturnboy** [comment]
@legshort releasing v0.15 shortly...
