### ISSUE TITLE
When You planned to release new version on PyPI ?

### ISSUE THREAD

**Issue by RockBomber** [ActivisionGameScience/assertpy#63]
Hello!
When You planned to release new version on PyPI, e.g. 0.11?

**Comment by saturnboy** [comment]
@RockBomber sorry! i'll push out v0.11 next week, only significant update is the `soft_fail()` changes you contributed

**Comment by saturnboy** [comment]
Released!  https://pypi.python.org/pypi/assertpy/0.11
