### ISSUE TITLE
regular expression flags on matches function

### ISSUE THREAD

**Issue by esbenrug** [ActivisionGameScience/assertpy#80]
It would be very beneficial to be able to give regular expression flags like MULTILINE as input to the 'matches' function.

**Comment by saturnboy** [comment]
@esbenrug you can already specify regex flags using "inline flags" in your pattern...

For example:

```py
import re

s = """bar
foo
baz"""

# matches
a = re.search(r'^foo$', s, re.MULTILINE)

# matches, using inline flag (?m)
b = re.search(r'(?m)^foo$', s)

# no match (aka returns None)
c = re.search(r'^foo$', s)
```
