### ISSUE TITLE
Add "using_tolerance" for easier float comparisons

### ISSUE THREAD

**Issue by j2kun** [ActivisionGameScience/assertpy#81]
I've been using `assertpy` for a while (it's great!!) and the one pesky thing that I wish assertpy had is to enable tolerant floating point comparisons for the life of an assertion.

A simple but illustrative example is when using nested tuples, sets, lists, and dictionaries involving floats.

```python
expected_point_list = tested_fn()
actual_point_list = [(4, -5.1), (1.2, 4), (5.5, 4)]

assert_that(expected_point_list).using_tolerance(1e-9).is_close_to(actual_point_list)
```

To do this without such a method requires many loops

```python
expected_point_list = tested_fn()
actual_point_list = [(4, -5.1), (1.2, 4), (5.5, 4)]

for (p1, p2) in zip(expected_point_list, actual_point_list):
  for (a, b) in zip(p1, p2):
    assert_that(a).is_close_to(b, 1e-9)
```

It's more complicated to do this when using sets, where iteration isn't deterministic. At each extra level of complication, it's harder to read, easier to mix up the expected and actual values, and harder to debug. If the above fails on the value 4, which index does it correspond to? This feature would enable that.

**Comment by saturnboy** [comment]
@j2kun good idea...let me think on it.  i never much like chained function where the downstream is changed, so conceptually it feels more like a context (aka using `with`).  let me know if you have other ideas

**Comment by j2kun** [comment]
Ooh, I love context managers!

**Comment by saturnboy** [comment]
@j2kun been thinking about this issue for a bit...

As a first step, I added the ability to flatten nested iterables.  You can now use the `extracting` helper to exact iterable items _by index_, like this:

```py
points = ((1,2,3), (4,5,6), (7,8,9))
assert_that(points).extracting(0).is_equal_to([1, 4, 7])
assert_that(points).extracting(-1).is_equal_to([3, 6, 9])
```

**Comment by j2kun** [comment]
I'm not sure what you have in mind, but a more general option that might be simpler would be to allow me to specify (in the context manager) a class that will be used for all comparisons no matter how deeply they are nested. The callable could be required to implement, depending on the usage, functions for eq, ne, ge, le, etc, and then standard types could have the comparators provided for them.

However, this seems like it would require some care to ensure the user-provided comparator isn't given the wrong types. For example, I'd expect a custom context manager for ints to go all the way at the bottom of any collection type (nested list of lists of lists of...), but somehow be smarter if I'm intending to do comparisons of lists of ints.

Perhaps one could register the comparator for specific types?

Anyhow, just spitballing.

**Comment by saturnboy** [comment]
@j2kun new `assertpy` extension system (see [docs](https://github.com/ActivisionGameScience/assertpy#extension-system---adding-custom-assertions)) allows you to write your own assertions to do custom float comparisons as you see fit.

**Comment by j2kun** [comment]
Beautiful! Thank you for your support!
