### ISSUE TITLE
Enhance Dict Comparison

### ISSUE THREAD

**Issue by zaz600** [ActivisionGameScience/assertpy#87]
Now we have 2 options for is_equal_to: ignore and include

`assert_that({'a':1,'b':2}).is_equal_to({'a':1}, ignore='b')`
`assert_that({'a':1,'b':2}).is_equal_to({'a':1}, include='a')`

Sometimes we need to check that some keys are equals but other are different

Could you add 3d option smth like `excepting`
Example:
`assert_that({'a':1,'b':2}).is_equal_to({'a':1, 'b':3}, excepting='b')` - should be passed
`assert_that({'a':1,'b':2}).is_equal_to({'a':1, 'b':2}, excepting='b')` - should be failed

**Comment by saturnboy** [comment]
@zaz600 I think `ignore` is what you want...don't check entries that you don't want to check.  Does it not work in this case?

This passes:

```py
assert_that({'a':1,'b':2}).is_equal_to({'a':1,'b':3}, ignore='b')
```

**Comment by zaz600** [comment]
No.
This assertion passed:
`assert_that({'a':1,'b':2}).is_equal_to({'a':1,'b':3}, ignore='b')`

and this one passed too:
`assert_that({'a':1,'b':2}).is_equal_to({'a':1,'b':2}, ignore='b')`

I need to now that `b` is different. Now i do smth like that (this test failed as expected):

```
    def test_b_is_changed(self):
        ev_before = {'a': 1, 'b': 2, 'c': 3}
        ev_after =  {'a': 1, 'b': 2, 'c': 3}
        assert_that(ev_after).is_equal_to(ev_before, ignore='b')
        assert_that(ev_after["b"]).is_not_equal_to(ev_before["b"])
```

**Comment by saturnboy** [comment]
@zaz600 checking if items are equal is done by `is_equal_to()`...if instead you want to verify that items are _not_ equal, use `is_not_equal_to()` instead.

Right now `is_not_equal_to()` does _NOT_ support the dict comparison helpers like `ignore`.  What if I updated that to work like this:

```py
assert_that({'a':1,'b':2}).is_not_equal_to({'a':1,'b':3}, ignore='a')
```

This will pass when `b` is different, but will fail if `b` is equal.  Would that work for you?

**Comment by zaz600** [comment]
In this case i need to do that:
```
 ev_before = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}
 ev_after =  {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}
 assert_that(ev_after).is_equal_to(ev_before, ignore=['b', 'd'])
 assert_that(ev_after).is_not_equal_to(ev_before, ignore=['a', 'c', 'e', 'f'])
```
sometimes there are more than 10 keys in dicts :)

**Comment by saturnboy** [comment]
@zaz600 new assertpy extension system (see [docs](https://github.com/ActivisionGameScience/assertpy#extension-system---adding-custom-assertions)) allows you to write your own assertions to do custom dict comparisons as you see fit.
