### ISSUE TITLE
Is it really dead?

### ISSUE THREAD

**Issue by GiovanniGatti** [ActivisionGameScience/assertpy#91]
I have some experience with AssertJ and I just find out this awesome library. Although last commit doesn't like that old (Oct., 2018), when reading the documentation it starts with

> **Dead** simple assertions library [...]

Is it really dead? If yes, why? It seams to be going in the right direction...

Thank you in advance for the clarification.

**Comment by saturnboy** [comment]
"dead simple" is a phase that means "very simple"...but good point.
