### ISSUE TITLE
soft_assertions does not handle nesting

### ISSUE THREAD

**Issue by amitwer** [ActivisionGameScience/assertpy#92]
Nesting "with soft_assertions():" statement breaks the "soft" attribute of the parent (the inner soft assertion is terminating the process.
Code to reproduce the scenario: 

def nested():
    with soft_assertions():
        for i in range (1,10):
            with soft_assertions():
                print(i)
                assert_that(i).is_equal_to(12)
                assert_that(i).is_equal_to(14)
nested()

This code stops after printing '1', resulting in the 2 assertion errors, but does not continue the for loop. 

2nd use case - recursive function (which was my starting state), behaves in a similar way:

def assertme(i):
    if i == 0:
        return
    with soft_assertions():
        print(f'asserting number   {i}')
        assert_that(i).is_equal_to(16)
        assertme(i-1)

assertme(12)

Once the context closes with an error (i==1), this error is raised and breaches the entire call stack, resulting in:
AssertionError: soft assertion failures:
1. Expected <1> to be equal to <16>, but was not.

(I was expecting the entire 1-12 to be counted as failures

**Comment by saturnboy** [comment]
@amitwer this is correct behavior. i think nesting identical contexts in python is generally not supported. for example, you don't open a file and re-open that same file, or open a file recursively...it doesn't make sense.

**Comment by amitwer** [comment]
@saturnboy I don't see why would this be a 'correct' behaviour, unless there is an option of declaring different contexts for a soft assertion.  (the same as you can open context for multiple files, to stick with the same example. 

A valid use case would be in larger tests (system level, rather than unit tests). For instance - 
two validation functions called sometimes separately and sometimes together, each with multiple assertions. 

def validateA():
with soft_assertions():
   assert_that(foo).is_equal_to(bar)
   assert_that(bar).contains('a')


def validateB():
with soft_assertions():
   assert_that(foo2).is_equal_to(bar2)
   assert_that(bar2).contains('a')

def validate_all():
   with soft_assertions():
      validateA()
      validateB()


In addition, even if such nesting isn't supported, it should at least raise an error to let the user know the piece of code they've written is invalid

**Comment by saturnboy** [comment]
the above it _not_ a valid use case.  `soft_assertions()` is a single-use non-reentrant context manager...just like `open()`.

- update docs to make this more clear
- throw error that makes this more clear

**Comment by amitwer** [comment]
Thanks!
What would be the proper way to deal with this use case (two functions, each with soft_assertions, that are called sometimes separately and sometimes together)?

**Comment by saturnboy** [comment]
@amitwer i fixed it using some reference counting. now the `soft_assertions()` context manager should be fully reentrant.  could you please test with your original recursive function?

**Comment by amitwer** [comment]
Hi, 
I added a test with the recursive function (opened a pull request - feel free to reject it if you don't want the test in the suite), looks like it is working. Thanks.

Is there a release planned anytime soon?

**Comment by Ryuno-Ki** [comment]
@amitwer Using [code fences](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) could help read your Python code snippets.
