### ISSUE TITLE
is_subset_of does not work when superset has only one element

### ISSUE THREAD

**Issue by BritEitan** [ActivisionGameScience/assertpy#93]
assertpy version 0.14

when using is_subset_of on one element as the superset with size == 1  TypeError is raised

assert_that(['a']).is_subset_of(['a']) - works
assert_that(['a']).is_subset_of(['b', 'c']) - works

assert_that(['a']).is_subset_of(['b'])

File "<input>", line 1, in <module>
  File "/.virtualenvs/env/lib/python3.6/site-packages/assertpy/assertpy.py", line 770, in is_subset_of
    self._err('Expected <%s> to be subset of %s, but %s %s missing.' % (self.val, self._fmt_items(superset), self._fmt_items(missing), 'was' if len(missing) == 1 else 'were'))
  File "/.virtualenvs/env/lib/python3.6/site-packages/assertpy/assertpy.py", line 1109, in _fmt_items
    return '<%s>' % i[0]
TypeError: 'set' object does not support indexing

**Comment by saturnboy** [comment]
@BritEitan that's for the bug report...i'll take a look

**Comment by saturnboy** [comment]
@BritEitan fixed! could you please test?

**Comment by Fongeme** [comment]
It looks to be working, sorry for the delay, we only now migrated to 1.0
