### ISSUE TITLE
code structure?

### ISSUE THREAD

**Issue by amitwer** [ActivisionGameScience/assertpy#95]
Hi, 
When looking over the code I noticed that there is one huge file with all the assertions, and its quite difficult to find my way in it. 
So, before I try to sort things and open a PR, is there  a reason not to break it down to multiple classes? Since the user is only creating AssertionBuilder through the factory methods, it seems possible to either have Assertion inherit methods from a bunch of helper classes (FileAssertions, CollectionsAssertions, NumberASsertions etc.) or to initialize it with members that contain the implementation, so that the actual class will only have thin wrapper functions. 

example:
```py
def is_subset_of(val):
    self._collection_assertions.is_subset_of(val)
    return self
```

**Comment by saturnboy** [comment]
@amitwer if you wanted to submit a PR to reorganize...I'd be happy to take a look. I think a Mixin pattern is the correct way to reorganize the `AssertionBuilder`.
