### ISSUE TITLE
log warning for assert_warn

### ISSUE THREAD

**Issue by p-frolov** [ActivisionGameScience/assertpy#97]
Hello,
As I understood, now assert_warn just print message to stdout for warning.

https://github.com/ActivisionGameScience/assertpy/blob/master/assertpy/assertpy.py#L1104
```
        if self.kind == 'warn':
            print(out)
```

assert_warn - is a good idea but it's not useful in production.

I suppose to expand signature by following :
```
def assert_warn(val, description='', logger=None):
```

then, in error function:
```
        if self.kind == 'warn':
            if self.logger:
                logger.warning(out)
            else:
                print(out)  # actually it's better to print to stderr or use warning module
```
in this case we can pass particular logger (logging. getLogger('name') instance) or logging module to invoke warning() function. Or pass nothing to use default behavior.

**Comment by saturnboy** [comment]
@p-frolov I've been thinking about removing `assert_warn` completely...why would you write tests that only printed a warning and did nothing?  I'm interesting is knowing how logging help?

**Comment by p-frolov** [comment]
@saturnboy 
First of all thank you for this library and this answer.

Actually I use this library for "self diagnostic" code, to check variables/data in runtime, not for unit tests or such. And I use only assert_that from this library. Library gives convenient and understandable approach for checks and call chains. Description is very important and useful parameter for issues investigations. Also a lot of checks - very important.
Several examples:
`assert_that(db_pipe_run, 'db pipe run').is_not_none()`
`assert_that(completed_results_ids_set, f'{name.title()} results ids set').is_length(len(tasks_completed))`
`assert_that(fields, 'run fields to update').is_type_of(dict).is_not_empty()`
`assert_that(context).contains_key('foo', 'bar')`
`assert_that(context['measure']).is_in(*_MEASURES)`
in my case this library removes a lot of `if` statements and working with collections when I need details of errors.

**So about `assert_warn`** sometime I need to log warning about some not critical errors. And it will be great to use all `assert_that` functionality for that.
A bit changed example from my production system:
```
import logging
logger = logging.getLogger(__name__)

ids_in_conf = {1, 2, 3}  # some ids in config
ready_ids = {1, 2}  # processed ids (must contain all from config)

if len(ids_in_conf) != len(ready_ids):
    # something wrong, need to investigate but no need to stop
    logger.warning('No ready ids for ids in conf: %s', ids_in_conf - ready_ids)

# process ready_ids
```
I could use:
```
assert_warn(ready_ids, 'Ready ids').is_equal_to(ids_in_conf)
```
Result `[Ready ids] Expected <{1, 2}> to be equal to <{1, 2, 3}>, but was not.` is very useful for issue investigation to get context/details of warning.
it's more functional and short checking than `if`. But I cannot use the result of this checking without logging. Stdout and stderr are not useful in production as well as python warning module.
So I would like the following:
```
assert_warn(ready_ids, 'Ready ids', logger=logger).is_equal_to(ids_in_conf)
```

about `assert_that` - It's not necessary to use logging, because it raises exceptions and my program catches and logs them.

**Comment by saturnboy** [comment]
@p-frolov you're using it for defensive assertions! that's a use case that is now obvious once you mentioned it, but one that i did not consider.

after some reading, it seems like best practice is for `assertpy` to implement it's own logger (just like other 3rd-party libraries, see `requests` for example).  so instead of requiring the user (aka you) to pass in a logger, `assert_warn` would just log at `WARN` by default to stdout.

then if you wanted to turn off logging when using `assert_warn`, you must do:

```py
import logging
logging.getLogger('assertpy').setLevel(logging.ERROR)
```

would that work?

**Comment by p-frolov** [comment]
@saturnboy 
 `defensive assertions` thank you, I was looking for a name of this programming approach for a long time.

actually `assertpy` is not regular 3rd-party, like `requests`, etc.. because `assertpy` is used for "testing" code in other libraries and programs. Root of error in `requests` is in `requests`, root of error in test case of `assertpy` is in code using assertions.
so, for errors and warning related to `assertpy` - it's ok to use standard logging system,
but cases are tested by `assertpy` must be connected to programs or libraries.

for `assert_that` - everything ok, because in exception we have whole information: message (`what happened`) and stack trace (`where happened`).

for assert_warn - in your suggestion - we will have `what happened`, but we will not have `where happened`, because logger will be named `assertpy` - no way to investigate where the problem is.
another problem of using 'assertpy' logger: we have assertions everywhere - we cannot switch on/off all of them - we need to manage logging by modules we testing, not by assertion library. For instance we have 2 modules, and both uses assertions, we need to switch off one of the modules, but need to have messages from second. It's usual thing in a project.
So I think simplest way to show `where happened` is to give opportunity to set logger, in this case, in logs we can see name of logger and can find out where a problem happened.
Another way is to get module and line where warning happened, but anyway we need to have standard logging management by loggers names.

**Comment by saturnboy** [comment]
@p-frolov this should be everything you want. updated `assert_warn()` to log instead of print with a default logger to `stdout`, but support for passing in a custom logger.

updated docs here:
https://github.com/ActivisionGameScience/assertpy#just-a-warning

note that some stack frame magic was required to (hopefully) identify the proper callee site. this is exposed to library users via the `WarningLoggingAdapter` (see [assert.py](https://github.com/ActivisionGameScience/assertpy/blob/master/assertpy/assertpy.py#L130)). it would be a huge help if you could try it out and let me know if it works for your use case.  if yes, i'll cut v0.15 shortly.

**Comment by p-frolov** [comment]
@saturnboy thank you a lot, I have tested feature - it works as expected. I am going to use it in production.
```python
logger = logging.getLogger('test')
assert_warn([1], 'List of..', logger=logger).is_empty()
```
in log:
```
2020-02-04 10:04:59 6717:140504133240640 test                             - WARNING    - [List of..] Expected <[1]> to be empty, but was not.
```
